//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.08 at 10:37:22 PM MESZ 
//


package net.brandstaetter.sequenceprocessing.xmlconfig;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}configType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="fnafile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="qualfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="midlist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="primerlist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="mismatches" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="mid" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                   &lt;attribute name="primer" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="filters" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="minLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                     &lt;element name="maxNs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                     &lt;element name="avgQual" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                     &lt;element name="singleMID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="singlePrimer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="DRBsplitting" minOccurs="0">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                   &lt;attribute name="optimized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="trimming" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="quality" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="average">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="scoreUnder">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="allowedCount" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                                       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="windowUnder">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="windowSize" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
 *                                       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="afterPrimer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="fixed" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                             &lt;attribute name="from">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="front"/>
 *                                   &lt;enumeration value="back"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="median" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="motif" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="type" use="required">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="regex"/>
 *                                   &lt;enumeration value="match"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                             &lt;attribute name="cutpoint" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="all" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="smoothing" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="msa">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="percentage" use="required">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="grouping">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="percentage" use="required">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                             &lt;attribute name="consensusAsAnchor" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                             &lt;attribute name="anchorAsFiller" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="output">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all minOccurs="0">
 *                   &lt;element name="graphs" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="graph">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice maxOccurs="unbounded">
 *                                       &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="primer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="mid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/choice>
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="allgraphs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="mode">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="standard"/>
 *                       &lt;enumeration value="singleFile"/>
 *                       &lt;enumeration value="filePerMID"/>
 *                       &lt;enumeration value="filePerPrimer"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="extension" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="zip"/>
 *                       &lt;enumeration value="tar.gz"/>
 *                       &lt;enumeration value="tar.bz2"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mailto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fnafile",
    "qualfile",
    "midlist",
    "primerlist",
    "mismatches",
    "filters",
    "drBsplitting",
    "trimming",
    "smoothing",
    "output",
    "mailto"
})
@XmlRootElement(name = "config")
public class Config
    extends ConfigType
{

    @XmlElement(required = true, defaultValue = "1.TCA.454Reads.fna")
    protected String fnafile;
    @XmlElement(defaultValue = "1.TCA.454Reads.qual")
    protected String qualfile;
    @XmlElement(required = true)
    protected String midlist;
    @XmlElement(required = true)
    protected String primerlist;
    protected Config.Mismatches mismatches;
    protected Config.Filters filters;
    @XmlElement(name = "DRBsplitting", defaultValue = "false")
    protected Config.DRBsplitting drBsplitting;
    protected List<Config.Trimming> trimming;
    protected Config.Smoothing smoothing;
    @XmlElement(required = true)
    protected Config.Output output;
    @XmlElement(required = true)
    protected String mailto;

    /**
     * Gets the value of the fnafile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnafile() {
        return fnafile;
    }

    /**
     * Sets the value of the fnafile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnafile(String value) {
        this.fnafile = value;
    }

    /**
     * Gets the value of the qualfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualfile() {
        return qualfile;
    }

    /**
     * Sets the value of the qualfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualfile(String value) {
        this.qualfile = value;
    }

    /**
     * Gets the value of the midlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMidlist() {
        return midlist;
    }

    /**
     * Sets the value of the midlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMidlist(String value) {
        this.midlist = value;
    }

    /**
     * Gets the value of the primerlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerlist() {
        return primerlist;
    }

    /**
     * Sets the value of the primerlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerlist(String value) {
        this.primerlist = value;
    }

    /**
     * Gets the value of the mismatches property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Mismatches }
     *     
     */
    public Config.Mismatches getMismatches() {
        return mismatches;
    }

    /**
     * Sets the value of the mismatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Mismatches }
     *     
     */
    public void setMismatches(Config.Mismatches value) {
        this.mismatches = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Filters }
     *     
     */
    public Config.Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Filters }
     *     
     */
    public void setFilters(Config.Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the drBsplitting property.
     * 
     * @return
     *     possible object is
     *     {@link Config.DRBsplitting }
     *     
     */
    public Config.DRBsplitting getDRBsplitting() {
        return drBsplitting;
    }

    /**
     * Sets the value of the drBsplitting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.DRBsplitting }
     *     
     */
    public void setDRBsplitting(Config.DRBsplitting value) {
        this.drBsplitting = value;
    }

    /**
     * Gets the value of the trimming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trimming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrimming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Config.Trimming }
     * 
     * 
     */
    public List<Config.Trimming> getTrimming() {
        if (trimming == null) {
            trimming = new ArrayList<Config.Trimming>();
        }
        return this.trimming;
    }

    /**
     * Gets the value of the smoothing property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Smoothing }
     *     
     */
    public Config.Smoothing getSmoothing() {
        return smoothing;
    }

    /**
     * Sets the value of the smoothing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Smoothing }
     *     
     */
    public void setSmoothing(Config.Smoothing value) {
        this.smoothing = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Output }
     *     
     */
    public Config.Output getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Output }
     *     
     */
    public void setOutput(Config.Output value) {
        this.output = value;
    }

    /**
     * Gets the value of the mailto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailto() {
        return mailto;
    }

    /**
     * Sets the value of the mailto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailto(String value) {
        this.mailto = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *       &lt;attribute name="optimized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DRBsplitting {

        @XmlValue
        protected boolean value;
        @XmlAttribute
        protected Boolean optimized;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the optimized property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOptimized() {
            if (optimized == null) {
                return true;
            } else {
                return optimized;
            }
        }

        /**
         * Sets the value of the optimized property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOptimized(Boolean value) {
            this.optimized = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="minLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="maxNs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="avgQual" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="singleMID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="singlePrimer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minLength",
        "maxNs",
        "avgQual",
        "singleMID",
        "singlePrimer"
    })
    public static class Filters {

        @XmlElement(defaultValue = "-1")
        protected Integer minLength;
        @XmlElement(defaultValue = "-1")
        protected Integer maxNs;
        @XmlElement(defaultValue = "-1")
        protected Integer avgQual;
        protected String singleMID;
        protected String singlePrimer;

        /**
         * Gets the value of the minLength property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMinLength() {
            return minLength;
        }

        /**
         * Sets the value of the minLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMinLength(Integer value) {
            this.minLength = value;
        }

        /**
         * Gets the value of the maxNs property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMaxNs() {
            return maxNs;
        }

        /**
         * Sets the value of the maxNs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMaxNs(Integer value) {
            this.maxNs = value;
        }

        /**
         * Gets the value of the avgQual property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAvgQual() {
            return avgQual;
        }

        /**
         * Sets the value of the avgQual property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAvgQual(Integer value) {
            this.avgQual = value;
        }

        /**
         * Gets the value of the singleMID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSingleMID() {
            return singleMID;
        }

        /**
         * Sets the value of the singleMID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSingleMID(String value) {
            this.singleMID = value;
        }

        /**
         * Gets the value of the singlePrimer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSinglePrimer() {
            return singlePrimer;
        }

        /**
         * Sets the value of the singlePrimer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSinglePrimer(String value) {
            this.singlePrimer = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mid" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="primer" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Mismatches {

        @XmlAttribute
        protected Integer mid;
        @XmlAttribute
        protected Integer primer;

        /**
         * Gets the value of the mid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getMid() {
            if (mid == null) {
                return  0;
            } else {
                return mid;
            }
        }

        /**
         * Sets the value of the mid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMid(Integer value) {
            this.mid = value;
        }

        /**
         * Gets the value of the primer property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPrimer() {
            if (primer == null) {
                return  0;
            } else {
                return primer;
            }
        }

        /**
         * Sets the value of the primer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPrimer(Integer value) {
            this.primer = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all minOccurs="0">
     *         &lt;element name="graphs" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="graph">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice maxOccurs="unbounded">
     *                             &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="primer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="mid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/choice>
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="allgraphs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="mode">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="standard"/>
     *             &lt;enumeration value="singleFile"/>
     *             &lt;enumeration value="filePerMID"/>
     *             &lt;enumeration value="filePerPrimer"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="extension" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="zip"/>
     *             &lt;enumeration value="tar.gz"/>
     *             &lt;enumeration value="tar.bz2"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Output {

        protected Config.Output.Graphs graphs;
        protected Boolean allgraphs;
        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute
        protected String mode;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String filename;
        @XmlAttribute(required = true)
        protected String extension;

        /**
         * Gets the value of the graphs property.
         * 
         * @return
         *     possible object is
         *     {@link Config.Output.Graphs }
         *     
         */
        public Config.Output.Graphs getGraphs() {
            return graphs;
        }

        /**
         * Sets the value of the graphs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Config.Output.Graphs }
         *     
         */
        public void setGraphs(Config.Output.Graphs value) {
            this.graphs = value;
        }

        /**
         * Gets the value of the allgraphs property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAllgraphs() {
            return allgraphs;
        }

        /**
         * Sets the value of the allgraphs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAllgraphs(Boolean value) {
            this.allgraphs = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilename(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the extension property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtension() {
            return extension;
        }

        /**
         * Sets the value of the extension property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtension(String value) {
            this.extension = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="graph">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice maxOccurs="unbounded">
         *                   &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="primer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="mid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/choice>
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "graph"
        })
        public static class Graphs {

            @XmlElement(required = true)
            protected List<Config.Output.Graphs.Graph> graph;

            /**
             * Gets the value of the graph property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the graph property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGraph().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Config.Output.Graphs.Graph }
             * 
             * 
             */
            public List<Config.Output.Graphs.Graph> getGraph() {
                if (graph == null) {
                    graph = new ArrayList<Config.Output.Graphs.Graph>();
                }
                return this.graph;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice maxOccurs="unbounded">
             *         &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="primer" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="mid" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/choice>
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "allOrPrimerOrMid"
            })
            public static class Graph {

                @XmlElementRefs({
                    @XmlElementRef(name = "all", type = JAXBElement.class),
                    @XmlElementRef(name = "primer", type = JAXBElement.class),
                    @XmlElementRef(name = "mid", type = JAXBElement.class)
                })
                protected List<JAXBElement<? extends Serializable>> allOrPrimerOrMid;
                @XmlAttribute(required = true)
                protected String name;

                /**
                 * Gets the value of the allOrPrimerOrMid property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the allOrPrimerOrMid property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAllOrPrimerOrMid().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<? extends Serializable>> getAllOrPrimerOrMid() {
                    if (allOrPrimerOrMid == null) {
                        allOrPrimerOrMid = new ArrayList<JAXBElement<? extends Serializable>>();
                    }
                    return this.allOrPrimerOrMid;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="msa">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="percentage" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="0"/>
     *                       &lt;maxInclusive value="100"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="grouping">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="percentage" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="0"/>
     *                       &lt;maxInclusive value="100"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="consensusAsAnchor" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="anchorAsFiller" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msa",
        "grouping"
    })
    public static class Smoothing {

        protected Config.Smoothing.Msa msa;
        protected Config.Smoothing.Grouping grouping;

        /**
         * Gets the value of the msa property.
         * 
         * @return
         *     possible object is
         *     {@link Config.Smoothing.Msa }
         *     
         */
        public Config.Smoothing.Msa getMsa() {
            return msa;
        }

        /**
         * Sets the value of the msa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Config.Smoothing.Msa }
         *     
         */
        public void setMsa(Config.Smoothing.Msa value) {
            this.msa = value;
        }

        /**
         * Gets the value of the grouping property.
         * 
         * @return
         *     possible object is
         *     {@link Config.Smoothing.Grouping }
         *     
         */
        public Config.Smoothing.Grouping getGrouping() {
            return grouping;
        }

        /**
         * Sets the value of the grouping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Config.Smoothing.Grouping }
         *     
         */
        public void setGrouping(Config.Smoothing.Grouping value) {
            this.grouping = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="percentage" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="0"/>
         *             &lt;maxInclusive value="100"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="consensusAsAnchor" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="anchorAsFiller" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Grouping {

            @XmlAttribute(required = true)
            protected int percentage;
            @XmlAttribute
            protected Boolean consensusAsAnchor;
            @XmlAttribute
            protected Boolean anchorAsFiller;

            /**
             * Gets the value of the percentage property.
             * 
             */
            public int getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             */
            public void setPercentage(int value) {
                this.percentage = value;
            }

            /**
             * Gets the value of the consensusAsAnchor property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isConsensusAsAnchor() {
                if (consensusAsAnchor == null) {
                    return false;
                } else {
                    return consensusAsAnchor;
                }
            }

            /**
             * Sets the value of the consensusAsAnchor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setConsensusAsAnchor(Boolean value) {
                this.consensusAsAnchor = value;
            }

            /**
             * Gets the value of the anchorAsFiller property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isAnchorAsFiller() {
                if (anchorAsFiller == null) {
                    return true;
                } else {
                    return anchorAsFiller;
                }
            }

            /**
             * Sets the value of the anchorAsFiller property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAnchorAsFiller(Boolean value) {
                this.anchorAsFiller = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="percentage" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="0"/>
         *             &lt;maxInclusive value="100"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Msa {

            @XmlAttribute(required = true)
            protected int percentage;

            /**
             * Gets the value of the percentage property.
             * 
             */
            public int getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             */
            public void setPercentage(int value) {
                this.percentage = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="quality" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="average">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="scoreUnder">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="allowedCount" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                           &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="windowUnder">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="windowSize" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
     *                           &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="afterPrimer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="fixed" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="from">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="front"/>
     *                       &lt;enumeration value="back"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="median" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="motif" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="regex"/>
     *                       &lt;enumeration value="match"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="cutpoint" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="all" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quality",
        "afterPrimer",
        "fixed",
        "median",
        "motif"
    })
    public static class Trimming {

        protected Config.Trimming.Quality quality;
        @XmlElement(defaultValue = "false")
        protected Boolean afterPrimer;
        protected Config.Trimming.Fixed fixed;
        @XmlElement(defaultValue = "false")
        protected Boolean median;
        protected List<Config.Trimming.Motif> motif;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String target;

        /**
         * Gets the value of the quality property.
         * 
         * @return
         *     possible object is
         *     {@link Config.Trimming.Quality }
         *     
         */
        public Config.Trimming.Quality getQuality() {
            return quality;
        }

        /**
         * Sets the value of the quality property.
         * 
         * @param value
         *     allowed object is
         *     {@link Config.Trimming.Quality }
         *     
         */
        public void setQuality(Config.Trimming.Quality value) {
            this.quality = value;
        }

        /**
         * Gets the value of the afterPrimer property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAfterPrimer() {
            return afterPrimer;
        }

        /**
         * Sets the value of the afterPrimer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAfterPrimer(Boolean value) {
            this.afterPrimer = value;
        }

        /**
         * Gets the value of the fixed property.
         * 
         * @return
         *     possible object is
         *     {@link Config.Trimming.Fixed }
         *     
         */
        public Config.Trimming.Fixed getFixed() {
            return fixed;
        }

        /**
         * Sets the value of the fixed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Config.Trimming.Fixed }
         *     
         */
        public void setFixed(Config.Trimming.Fixed value) {
            this.fixed = value;
        }

        /**
         * Gets the value of the median property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMedian() {
            return median;
        }

        /**
         * Sets the value of the median property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMedian(Boolean value) {
            this.median = value;
        }

        /**
         * Gets the value of the motif property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the motif property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMotif().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.Trimming.Motif }
         * 
         * 
         */
        public List<Config.Trimming.Motif> getMotif() {
            if (motif == null) {
                motif = new ArrayList<Config.Trimming.Motif>();
            }
            return this.motif;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            if (target == null) {
                return "all";
            } else {
                return target;
            }
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="from">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="front"/>
         *             &lt;enumeration value="back"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Fixed {

            @XmlValue
            protected int value;
            @XmlAttribute
            protected String from;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFrom(String value) {
                this.from = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="regex"/>
         *             &lt;enumeration value="match"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="cutpoint" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Motif {

            @XmlValue
            protected String value;
            @XmlAttribute(required = true)
            protected String type;
            @XmlAttribute(required = true)
            protected int cutpoint;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the cutpoint property.
             * 
             */
            public int getCutpoint() {
                return cutpoint;
            }

            /**
             * Sets the value of the cutpoint property.
             * 
             */
            public void setCutpoint(int value) {
                this.cutpoint = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="average">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="scoreUnder">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="allowedCount" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *                 &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="windowUnder">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="windowSize" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
         *                 &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "average",
            "scoreUnder",
            "windowUnder"
        })
        public static class Quality {

            protected Config.Trimming.Quality.Average average;
            protected Config.Trimming.Quality.ScoreUnder scoreUnder;
            protected Config.Trimming.Quality.WindowUnder windowUnder;

            /**
             * Gets the value of the average property.
             * 
             * @return
             *     possible object is
             *     {@link Config.Trimming.Quality.Average }
             *     
             */
            public Config.Trimming.Quality.Average getAverage() {
                return average;
            }

            /**
             * Sets the value of the average property.
             * 
             * @param value
             *     allowed object is
             *     {@link Config.Trimming.Quality.Average }
             *     
             */
            public void setAverage(Config.Trimming.Quality.Average value) {
                this.average = value;
            }

            /**
             * Gets the value of the scoreUnder property.
             * 
             * @return
             *     possible object is
             *     {@link Config.Trimming.Quality.ScoreUnder }
             *     
             */
            public Config.Trimming.Quality.ScoreUnder getScoreUnder() {
                return scoreUnder;
            }

            /**
             * Sets the value of the scoreUnder property.
             * 
             * @param value
             *     allowed object is
             *     {@link Config.Trimming.Quality.ScoreUnder }
             *     
             */
            public void setScoreUnder(Config.Trimming.Quality.ScoreUnder value) {
                this.scoreUnder = value;
            }

            /**
             * Gets the value of the windowUnder property.
             * 
             * @return
             *     possible object is
             *     {@link Config.Trimming.Quality.WindowUnder }
             *     
             */
            public Config.Trimming.Quality.WindowUnder getWindowUnder() {
                return windowUnder;
            }

            /**
             * Sets the value of the windowUnder property.
             * 
             * @param value
             *     allowed object is
             *     {@link Config.Trimming.Quality.WindowUnder }
             *     
             */
            public void setWindowUnder(Config.Trimming.Quality.WindowUnder value) {
                this.windowUnder = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Average {

                @XmlAttribute(required = true)
                protected int threshold;

                /**
                 * Gets the value of the threshold property.
                 * 
                 */
                public int getThreshold() {
                    return threshold;
                }

                /**
                 * Sets the value of the threshold property.
                 * 
                 */
                public void setThreshold(int value) {
                    this.threshold = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="allowedCount" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
             *       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ScoreUnder {

                @XmlAttribute
                protected Integer allowedCount;
                @XmlAttribute(required = true)
                protected int threshold;

                /**
                 * Gets the value of the allowedCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getAllowedCount() {
                    if (allowedCount == null) {
                        return  1;
                    } else {
                        return allowedCount;
                    }
                }

                /**
                 * Sets the value of the allowedCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setAllowedCount(Integer value) {
                    this.allowedCount = value;
                }

                /**
                 * Gets the value of the threshold property.
                 * 
                 */
                public int getThreshold() {
                    return threshold;
                }

                /**
                 * Sets the value of the threshold property.
                 * 
                 */
                public void setThreshold(int value) {
                    this.threshold = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="windowSize" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
             *       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class WindowUnder {

                @XmlAttribute
                protected Integer windowSize;
                @XmlAttribute(required = true)
                protected int threshold;

                /**
                 * Gets the value of the windowSize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getWindowSize() {
                    if (windowSize == null) {
                        return  5;
                    } else {
                        return windowSize;
                    }
                }

                /**
                 * Sets the value of the windowSize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setWindowSize(Integer value) {
                    this.windowSize = value;
                }

                /**
                 * Gets the value of the threshold property.
                 * 
                 */
                public int getThreshold() {
                    return threshold;
                }

                /**
                 * Sets the value of the threshold property.
                 * 
                 */
                public void setThreshold(int value) {
                    this.threshold = value;
                }

            }

        }

    }

}
