//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.08 at 10:37:22 PM MESZ 
//


package net.brandstaetter.sequenceprocessing.xmlconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.brandstaetter.sequenceprocessing.xmlconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigOutputGraphsGraphMid_QNAME = new QName("", "mid");
    private final static QName _ConfigOutputGraphsGraphPrimer_QNAME = new QName("", "primer");
    private final static QName _ConfigOutputGraphsGraphAll_QNAME = new QName("", "all");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.brandstaetter.sequenceprocessing.xmlconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Config.Trimming }
     * 
     */
    public Config.Trimming createConfigTrimming() {
        return new Config.Trimming();
    }

    /**
     * Create an instance of {@link Config.Trimming.Quality.WindowUnder }
     * 
     */
    public Config.Trimming.Quality.WindowUnder createConfigTrimmingQualityWindowUnder() {
        return new Config.Trimming.Quality.WindowUnder();
    }

    /**
     * Create an instance of {@link Config.Trimming.Fixed }
     * 
     */
    public Config.Trimming.Fixed createConfigTrimmingFixed() {
        return new Config.Trimming.Fixed();
    }

    /**
     * Create an instance of {@link Config.Smoothing }
     * 
     */
    public Config.Smoothing createConfigSmoothing() {
        return new Config.Smoothing();
    }

    /**
     * Create an instance of {@link Config.Output.Graphs.Graph }
     * 
     */
    public Config.Output.Graphs.Graph createConfigOutputGraphsGraph() {
        return new Config.Output.Graphs.Graph();
    }

    /**
     * Create an instance of {@link Config.DRBsplitting }
     * 
     */
    public Config.DRBsplitting createConfigDRBsplitting() {
        return new Config.DRBsplitting();
    }

    /**
     * Create an instance of {@link Config.Output.Graphs }
     * 
     */
    public Config.Output.Graphs createConfigOutputGraphs() {
        return new Config.Output.Graphs();
    }

    /**
     * Create an instance of {@link Config.Trimming.Motif }
     * 
     */
    public Config.Trimming.Motif createConfigTrimmingMotif() {
        return new Config.Trimming.Motif();
    }

    /**
     * Create an instance of {@link Config.Trimming.Quality.ScoreUnder }
     * 
     */
    public Config.Trimming.Quality.ScoreUnder createConfigTrimmingQualityScoreUnder() {
        return new Config.Trimming.Quality.ScoreUnder();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link Config.Filters }
     * 
     */
    public Config.Filters createConfigFilters() {
        return new Config.Filters();
    }

    /**
     * Create an instance of {@link Config.Smoothing.Msa }
     * 
     */
    public Config.Smoothing.Msa createConfigSmoothingMsa() {
        return new Config.Smoothing.Msa();
    }

    /**
     * Create an instance of {@link Config.Trimming.Quality.Average }
     * 
     */
    public Config.Trimming.Quality.Average createConfigTrimmingQualityAverage() {
        return new Config.Trimming.Quality.Average();
    }

    /**
     * Create an instance of {@link Config.Smoothing.Grouping }
     * 
     */
    public Config.Smoothing.Grouping createConfigSmoothingGrouping() {
        return new Config.Smoothing.Grouping();
    }

    /**
     * Create an instance of {@link Config.Output }
     * 
     */
    public Config.Output createConfigOutput() {
        return new Config.Output();
    }

    /**
     * Create an instance of {@link Config.Mismatches }
     * 
     */
    public Config.Mismatches createConfigMismatches() {
        return new Config.Mismatches();
    }

    /**
     * Create an instance of {@link Config.Trimming.Quality }
     * 
     */
    public Config.Trimming.Quality createConfigTrimmingQuality() {
        return new Config.Trimming.Quality();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mid", scope = Config.Output.Graphs.Graph.class)
    public JAXBElement<String> createConfigOutputGraphsGraphMid(String value) {
        return new JAXBElement<String>(_ConfigOutputGraphsGraphMid_QNAME, String.class, Config.Output.Graphs.Graph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "primer", scope = Config.Output.Graphs.Graph.class)
    public JAXBElement<String> createConfigOutputGraphsGraphPrimer(String value) {
        return new JAXBElement<String>(_ConfigOutputGraphsGraphPrimer_QNAME, String.class, Config.Output.Graphs.Graph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "all", scope = Config.Output.Graphs.Graph.class)
    public JAXBElement<Boolean> createConfigOutputGraphsGraphAll(Boolean value) {
        return new JAXBElement<Boolean>(_ConfigOutputGraphsGraphAll_QNAME, Boolean.class, Config.Output.Graphs.Graph.class, value);
    }

}
